<?php
// $Id$

/**
 * @file
 * Facebook Connector module
 */


/* ************************************************************************* *
 * THEME FUNCTIONS
 * ************************************************************************* */

/**
 * Implementation of hook_theme().
 */
function fbconnector_theme() {
  $theme = array(
    'fbconnector_button' => array(
      'arguments' => array(),
    ),
  );

  return $theme;
}

/**
 * Theme function for the button
 */
function theme_fbconnector_button() {
  drupal_add_js(drupal_get_path('module', 'fbconnector') . '/fbconnector.js', 'theme', 'footer');
  return '<fb:login-button onlogin="fbconnector_login();"></fb:login-button>';
}


/* ************************************************************************* *
 * DRUPAL HOOKS
 * ************************************************************************* */

/**
 * Implementation of hook_connector().
 */
function fbconnector_connector() {
  $items = array();

  if (variable_get('fbconnector_api_key', NULL) && variable_get('fbconnector_application_secret', NULL)) {
    $items['fbconnector'] = array(
      'title'                => 'Facebook',
      'button callback'      => '_fbconnector_button',
      'id callback'          => '_fbconnector_id',
      'logout callback'      => '_fbconnector_logout',
      'information callback' => '_fbconnector_info',
      'avatar callback'      => '_fbconnector_avatar',
      'cache'                => 72000, //20 hours x 3600 seconds per hour
      'invalidate old info'  => TRUE,
    );
  }

  return $items;
}

/**
 * Implementation of hook_menu().
 */
function fbconnector_menu() {
  $items['admin/settings/fbconnector'] = array(
    'title'            => 'Facebook Connector',
    'description'      => "Configure the API credentials Facebook Connector needs to talk with Facebook.",
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('fbconnector_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file'             => 'fbconnector.admin.inc',
  );

  $items['admin/settings/fbconnector/settings'] = array(
    'title'  => 'Settings',
    'type'   => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['admin/settings/fbconnector/setup'] = array(
    'title'            => 'Auto-configure',
    'type'             => MENU_LOCAL_TASK,
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('fbconnector_setup_form'),
    'access arguments' => array('administer site configuration'),
    'weight'           => 0,
    'file'             => 'fbconnector.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_init().
 */
function fbconnector_init() {
  global $user;

  if ($user->uid == 0) {
    try {
      if (_fbconnector_client()->get_loggedin_user()) {
        if (_connector_log_in('fbconnector')) {
          $info = _connector_information_fetch($user->uid, array('real name' => TRUE));
          if (empty($info['real name'])) {
            _connector_information_update($user->uid, array('real name' => TRUE));
          }
          drupal_goto($_GET['q']);
        }
      }
    } catch (Exception $e) {
      watchdog('fbconnector', 'Caught Facebook Client exception: @exception',  array('@exception' => $e->getMessage()), WATCHDOG_WARNING);
    }
  }
}

/**
 * Implementation of hook_footer().
 */
function fbconnector_footer() {
  return '<script type="text/javascript" src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php"></script>';
}

/**
 * Implementation of hook_form_alter().
 */
function fbconnector_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'connector_button_form' && isset($form['fbconnector'])) {
    $form['fbconnector']['#attributes'] = array('style' => 'display: none;');
    if (!isset($form['fbconnector']['#pre_render'])) {
      $form['fbconnector']['#pre_render'] = array();
    }
    array_unshift($form['fbconnector']['#pre_render'], 'fbconnector_button_pre_render');
  }
}

/* ************************************************************************* *
 * FACEBOOK INTEGRATION
 * ************************************************************************* */

function _fbconnector_client() {
  static $fb = NULL;
  if (!$fb instanceof Facebook) {
    if (!class_exists('Facebook')) {
      include_once(drupal_get_path('module', 'fbconnector') . '/facebook-platform/facebook.php');
    }
    $fb = new Facebook(variable_get('fbconnector_api_key', NULL), variable_get('fbconnector_application_secret', NULL));
  }
  return $fb;
}

/**
 * Avatar callback
 */
function _fbconnector_avatar($connector, $cid) {
  try {
    $result = _fbconnector_client()->api_client->users_getInfo($cid, array(
      'pic_square_with_logo',
    ));
  }
  catch (FacebookRestClientException $e) {
    return FALSE;
  }
  return empty($result) ? FALSE : $result[0]['pic_square_with_logo'];
}

/**
 * Information callback
 */
function _fbconnector_info($connector, $cid, $types = NULL) {
  $info = array();

  if (empty($types) || !empty($types['real name'])) {
    try {
      $result = _fbconnector_client()->api_client->users_getInfo($cid, array(
        'name',
      ));
    }
    catch (FacebookRestClientException $e) {
      return FALSE;
    }
    $info['real name'] = empty($result) ? FALSE : $result[0]['name'];
  }

  return $info;
}

/**
 * Logout callback
 */
function _fbconnector_logout($connector, $cid) {
  $client = _fbconnector_client();
  if ($client->get_loggedin_user() == $cid) {
    $client->clear_cookie_state();
  }
}

/**
 * Connector ID callback
 */
function _fbconnector_id($connector) {
  return _fbconnector_client()->get_loggedin_user();
}

/**
 * Connector button callback
 */
function _fbconnector_button($form, &$form_state) {
  // Intentionally left blank - we don't do anything on the form submit itself
  // We do it in hook_init() and redirects prior to getting here.
}

function fbconnector_button_pre_render($element) {
  drupal_add_js(array(
    'fbconnector_api_key'     => variable_get('fbconnector_api_key', NULL),
    'fbconnector_xd_receiver' => check_plain(base_path() . drupal_get_path('module', 'fbconnector') . '/xd_receiver.htm'),
  ), 'setting');
  $element['#prefix'] = theme('fbconnector_button');
  return $element;
}